---
- name: Ensure minimal deps are available
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - git
    - build-essential

- name: Clone repo
  ansible.builtin.git:
    repo: "{{ capstone_url }}"
    dest: "{{ capstone_root }}"
    version: "{{ capstone_revision | default('master') }}"
    depth: "{{ git_clone_depth | default(omit) }}"
    force: "{{ force_clone }}"
  tags:
    - clone

- name: Build capstone
  ansible.builtin.shell: make -j$(nproc)
  args:
    chdir: "{{ capstone_root }}"
  when: not ansible_check_mode
  tags:
    - build

- name: Install capstone
  ansible.builtin.shell: make install
  args:
    chdir: "{{ capstone_root }}"
  become: true
  when: not ansible_check_mode
  tags:
    - build
