- name: Install KVM-Nyx kernel build dependencies
  ansible.builtin.package:
    name:
      - build-essential
      - flex
      - bison
      - libelf-dev
      - libssl-dev
      - bc
      - dwarves
      - zstd
  become: true

- name: Clone KVM-Nyx source
  ansible.builtin.git:
    repo: "{{ kvm_nyx_url }}"
    dest: "{{ kvm_nyx_root }}"
    version: "{{ kvm_nyx_revision | default('kvm-nyx-6.8') }}"
    depth: "{{ git_clone_depth | default(omit) }}"
    force: "{{ force_clone }}"
  tags:
    - clone

- name: Build full KVM-Nyx kernel
  ansible.builtin.shell: make -j$(nproc)
  args:
    chdir: "{{ kvm_nyx_root }}"
  when: not ansible_check_mode
  tags:
    - build

- name: Install KVM-Nyx kernel modules
  ansible.builtin.command: make modules_install
  args:
    chdir: "{{ kvm_nyx_root }}"
  become: true
  when: not ansible_check_mode
  tags:
    - build

- name: Install KVM-Nyx kernel
  ansible.builtin.command: make install
  args:
    chdir: "{{ kvm_nyx_root }}"
  become: true
  when: not ansible_check_mode
  tags:
    - build

- name: Update GRUB to boot KVM-Nyx kernel
  ansible.builtin.command: update-grub
  become: true
  when: not ansible_check_mode
  tags:
    - build

- name: Reboot into KVM-Nyx kernel
  ansible.builtin.reboot:
  become: true
  when: not ansible_check_mode and ansible_connection != 'local'
  tags:
    - build
    - reboot_kernel
